name: reltgws-efkot          # уникальное глобально — не повтори чужое/своё старое
services:
  relay0:
    image: golang
    version: "1.22"
    size: mili               # НЕ pico: под go build нужна память
    active: true
    restart: always
    git:
      url: https://github.com/efkot-dev/RelTg.git
      branch: main
    pwd: .
    command: go build -o /relay . && exec /relay
    ports:
      - port: 8080
        type: proxy
    environment:
      - PORT=8080
      - RELAY_TOKEN=5E7Eky2fkshECG